import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	// CHANGE: Two entry points mapping to specific output names
	entryPoints: [
		{ in: "src/main.ts", out: "main" },
		{ in: "src/workers/embedding.worker.ts", out: "worker" }
	],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2020", // Bumped slightly for better worker support
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	// CHANGE: Use outdir instead of outfile to support multiple outputs
	outdir: ".", 
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}