import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import inlineWorkerPlugin from "esbuild-plugin-inline-worker";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// 1. Main Process Externals (Obsidian Desktop)
const mainExternalModules = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
	"onnxruntime-node",
	...builtinModules.filter(m => m !== 'events'),
	...builtinModules.filter(m => m !== 'events').map(m => `node:${m}`)
];

// 2. Worker Process Externals (Browser)
// We keep 'obsidian' external just in case, but we mock everything else.
const workerExternalModules = [
	"obsidian",
	"electron",
];

// 3. Mock Plugin
// Replaces Node.js dependencies with empty objects to prevent 'Module not found' errors.
// File mocks: whole modules whose top-level body is unsafe for browser bundles
// (they use `node:` imports or bare `process` access at module scope and are
// dead code in-plugin, selected only when IS_NODE_ENV is true).
const mockPlugin = {
	name: 'mock-plugin',
	setup(build) {
		build.onResolve({ filter: /^(sharp|onnxruntime-node|fs|path|url|child_process|stream|stream\/promises|node:fs|node:path|node:url|node:child_process|node:stream|node:stream\/promises)$/ }, args => ({
			path: args.path,
			namespace: 'mock-ns'
		}));
		
		// Transformers.js >= 4.3 ships `src/backends/onnx-node.js`: a Node-only ONNX
		// backend whose module body imports 'node:module' and touches bare `process.env`
		// at the top level. `src/backends/onnx.js` statically imports it, so specifier
		// mocks alone cannot keep it safe: the evaluated expression `import.meta.url ??
		// __filename` would still ship to the worker bundle. Instead, resolve the whole
		// file into the mock namespace: it is dead code in-plugin (only reachable when
		// IS_NODE_ENV is true, which the `define` overrides below make impossible).
		build.onResolve({ filter: /onnx-node\.js$/ }, args => ({
			path: args.path,
			namespace: 'mock-ns'
		}));

		build.onLoad({ filter: /.*/, namespace: 'mock-ns' }, () => ({
			contents: 'module.exports = {};',
			loader: 'js'
		}));
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: mainExternalModules,
	alias: {
		"@huggingface/transformers/src": "./node_modules/@huggingface/transformers/src",
		"@huggingface/transformers": "./node_modules/@huggingface/transformers/src/transformers.js"
	},
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	define: {
		'process.release.name': '"browser"',
		'process.versions.node': 'false' 
	},
	plugins: [
		mockPlugin,
		inlineWorkerPlugin({
			bundle: true,
			format: 'iife',
			platform: 'browser',
			target: 'es2020',
			minify: prod,
			external: workerExternalModules,
			alias: {
				"@huggingface/transformers/src": "./node_modules/@huggingface/transformers/src",
				"@huggingface/transformers": "./node_modules/@huggingface/transformers/src/transformers.js"
			},
			// [!code ++] CRITICAL FIX: Force library to detect "browser" environment
			define: {
				'process.release.name': '"browser"',
				'process.versions.node': 'false' 
			},
			plugins: [mockPlugin]
		})
	]
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}