declare module '@orama/stopwords/arabic' { export const stopwords: string[]; }
declare module '@orama/stopwords/armenian' { export const stopwords: string[]; }
declare module '@orama/stopwords/bulgarian' { export const stopwords: string[]; }
declare module '@orama/stopwords/chinese' { export const stopwords: string[]; }
declare module '@orama/stopwords/danish' { export const stopwords: string[]; }
declare module '@orama/stopwords/dutch' { export const stopwords: string[]; }
declare module '@orama/stopwords/english' { export const stopwords: string[]; }
declare module '@orama/stopwords/finnish' { export const stopwords: string[]; }
declare module '@orama/stopwords/french' { export const stopwords: string[]; }
declare module '@orama/stopwords/german' { export const stopwords: string[]; }
declare module '@orama/stopwords/greek' { export const stopwords: string[]; }
declare module '@orama/stopwords/hindi' { export const stopwords: string[]; }
declare module '@orama/stopwords/hungarian' { export const stopwords: string[]; }
declare module '@orama/stopwords/indonesian' { export const stopwords: string[]; }
declare module '@orama/stopwords/irish' { export const stopwords: string[]; }
declare module '@orama/stopwords/italian' { export const stopwords: string[]; }
declare module '@orama/stopwords/nepali' { export const stopwords: string[]; }
declare module '@orama/stopwords/norwegian' { export const stopwords: string[]; }
declare module '@orama/stopwords/portuguese' { export const stopwords: string[]; }
declare module '@orama/stopwords/romanian' { export const stopwords: string[]; }
declare module '@orama/stopwords/russian' { export const stopwords: string[]; }
declare module '@orama/stopwords/sanskrit' { export const stopwords: string[]; }
declare module '@orama/stopwords/serbian' { export const stopwords: string[]; }
declare module '@orama/stopwords/slovenian' { export const stopwords: string[]; }
declare module '@orama/stopwords/spanish' { export const stopwords: string[]; }
declare module '@orama/stopwords/swedish' { export const stopwords: string[]; }
declare module '@orama/stopwords/tamil' { export const stopwords: string[]; }
declare module '@orama/stopwords/turkish' { export const stopwords: string[]; }
declare module '@orama/stopwords/ukrainian' { export const stopwords: string[]; }
